import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'

const handleClick = () => {
  console.log("what is up bro");
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner btntext="view nearby stores" handleClick={handleClick} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">CCD!</a>
        </h1>
      </main>


    </div>
  )
}
