import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner";
import Card from "../components/card";

const handleClick = () => {
  console.log("what is up bro");
}

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          btntext="view nearby stores"
          handleClick={handleClick} />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400} />
        </div>
        <Card
          imgURL="/static/hero-image.png"
          name="Card component"
          href="/coffee-store/darkhouse-coffee" />
      </main>
    </div>
  )
}
