import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner";
import Card from "../components/card";
import coffeeData from "../data/coffee-stores.json";

export async function getStaticProps(context) {



  const searchParams = new URLSearchParams({
    query: 'coffee',
    ll: '28.63412421042539,77.21353641789399'
  });
  const results = await fetch(
    `https://api.foursquare.com/v3/places/search?${searchParams}&limit=6`,
    {
      method: 'GET',
      headers: {
        Accept: 'application/json',
        Authorization: 'fsq3kdGD9xgJITIEmEyBcs7laFbChZWM9lya4JJC+9IkA30=',
      }
    }
  );
  const data = await results.json();
  console.log("api data", data.results);;
  return {
    props: { coffee: data.results }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  // console.log(props);
  const handleOnBannerBtnClick = () => {
    console.log("whats up bro");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>

        {props.coffee.length > 0 && (
          <>
            <h2 className={styles.heading2}>Delhi stores</h2>
            <div className={styles.cardLayout}>
              {props.coffee.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}